// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSNUSqlXVFByNYQp4MfsR0Cg7DCi55OQA',
    appId: '1:609577994134:web:6e376eaf357b9eaf58ffb7',
    messagingSenderId: '609577994134',
    projectId: 'myname-a73b1',
    authDomain: 'myname-a73b1.firebaseapp.com',
    databaseURL: 'https://myname-a73b1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myname-a73b1.firebasestorage.app',
    measurementId: 'G-H5HKFZ9CKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4ac1HRfefaQ1MQBNUeKFc_-KmkomGXkY',
    appId: '1:609577994134:android:be182978836728a158ffb7',
    messagingSenderId: '609577994134',
    projectId: 'myname-a73b1',
    databaseURL: 'https://myname-a73b1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myname-a73b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD1wL8guBj4gnMyN8iwJoIYLLf_EocOlA',
    appId: '1:609577994134:ios:3c721636e570056158ffb7',
    messagingSenderId: '609577994134',
    projectId: 'myname-a73b1',
    databaseURL: 'https://myname-a73b1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myname-a73b1.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

}